services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27019:27017
    volumes:
      - /Users/mongo/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=cognizant
    restart: always
    networks:
      - zeus-net
      - sapphire-net
      - infrastructure
      - artemis-net
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 9091:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=cognizant
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: always
    networks:
      - zeus-net
      - sapphire-net
      - infrastructure
      - artemis-net
networks:
  zeus-net:
    external: true
  sapphire-net:
    external: true
  infrastructure:
    external: true
  artemis-net:
    external: true
