services:
  neo4j:
    image: neo4j:5.19.0-enterprise  # Specific version of Neo4j Enterprise Edition
    container_name: neo4j
    ports:
      - "7475:7474"       # HTTP (Neo4j Browser)
      - "7688:7687"       # Bolt protocol
    volumes:
      - neo4j_data:/data           # Persist data files
      - neo4j_logs:/logs           # Persist log files
      - neo4j_import:/import       # Import data
      - neo4j_conf:/var/lib/neo4j/conf  # Optional: Custom configuration
    environment:
      - NEO4J_AUTH=neo4j/password          # Set admin username and password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes  # Accept Enterprise license
      - NEO4J_dbms_memory_pagecache_size=2G # Configure memory for caching
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]  # Include popular plugins
    restart: always
    networks:
      - sapphire-net

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_conf:
networks:
  sapphire-net:
    external: true