version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
#    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    mem_limit: 1g
    networks:
      - sapphire-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
#    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - sapphire-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    container_name: logstash
#    restart: always
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ../sapphire/logs:/sapphire/logs
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - sapphire-net

volumes:
  es_data:
    driver: local

networks:
  sapphire-net:
    external: true