services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres # this is the admin user
      POSTGRES_PASSWORD: cognizant # this is the admin password
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - infrastructure
networks:
  infrastructure:
    external: true